### ISSUE TITLE
Refactor Swagger endpoionts

### ISSUE THREAD

**Issue by mzraatik** [OpenReqEU/mulperi#2]
Now the endpoints are quite generally named. Change the names to more descriptive and hide unnecessary ones. Notify and agree with TUGraz.

**Comment by Harrihauki** [comment]
Old endpoints hidden from Swagger UI. requirementsToChoco method's name changed to murmeliModelToKeljuCaaS and updateModel method's name changed to updateMurmeliModelInKeljuCaaS.
